DATE_FORMAT = 'd/M/Y'
TIME_FORMAT = 'H:i'
DATETIME_FORMAT = 'd/m/Y H:i'
# YEAR_MONTH_FORMAT
# MONTH_DAY_FORMAT
# SHORT_DATE_FORMAT
# SHORT_DATETIME_FORMAT
# FIRST_DAY_OF_WEEK
# DECIMAL_SEPARATOR
# THOUSAND_SEPARATOR
# NUMBER_GROUPING.